# Generated by Django 2.2 on 2020-11-30 09:23

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=app.models.Profile.avatar_filename, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='Like or not'),
        ),
    ]
